sudo: required
language: java
notifications:
  email: false
jdk:
- oraclejdk11
services:
- docker
script:
- ".travis/build.sh $VERSION $COMMIT"
env:
  global:
  - VERSION=10-1
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: JjMRw8EWq4xJhVSfLFmvji8b2ZEOKjuE9utDLjSt8Oqv+wp0YI06YURSVe9PB/+E7eezqekKGejP5V8zNsqegyIcbDwW1SO/kGT4A91RiWme9/m+nRvuIlt3Uk1kwv0ep8dS9aBKRgJ+doUm1G9F0lnwJ0V9h7uIkLgTq4wI4Ed0O7Sq5ngaMLB37iaMwzlIXpVPfhzSNk5U2aaxbkSKGRhkGHdMT6jbaO3KKiP5tAQpEkplMjf4dcQ75pGE2fncgrDdf7JubT+HIeNPMnE3u70xmmPCYIrmsoc70HLnmUv++kOSvd5UICNO1z03aEdqQGNMR7SSwio3N3hQLSgoBuCf1owl5hmFgRSP495A5Ev4NqWLz5SgMgpsZhVV7OFFgGMe/JX7Lyr0WnDJZwkumll2FWg7PDC0HetEyVBAq+b5wP2oyvAv+DUp/x83YdfD1hj/q1FmfyGwqnkLMKnxAneM01J4vlXtTfB/uvEYYgsflbrpCPPnmJyKu3271raMf81KYlaqsFOnd2rsAqQqjA9vKnvmkeE8tLBhpHey8DVuCn9Qx3q4/UuLPnFmmhRgB/4ukmBAOIJC1u9Cf6kva8h2F1GVEw38L9dsGlB3P+fBHkCi0zAfXuxN+eF68+h2n0R3vnFM3loG5Dx9FxEBdL8ggOf9NWTj5R3yMaZ9QIY=
  - secure: le2EnpBbc4LQa+jQ4ZUThT+NP24mnlZhn5pda3vp4W1JZ64zlJeR5BuHTv1B8beZ34R+5uAaZ1x1OzHF6i0PoIoj51yQQ58lhNcCfLJaPwJv0OA4EUHMUsvDbke+S1IKqCF0aH6UaXjGAONjzflyHR/sJN8KKP06105nU83F+kHAg+hGE4p2O1lP1rNNWMeVpZL/gYJ6IXDWy0Ql5jGrb5VrPm0kQthE1lk2S2LX6EYLRtptoJVV+yA0nH85OGBi7ckGKR41B6LLge9rsgrNL4M2pjGinUryUOfORW0e5nMetcByIbLBrkLF3KSY0MhvgzSrwpN91H9Vz3uzULlh100h/3++CGLzx949+15tE0ECr8Y6a1yNco79sZWViOtmuqQYFwzvE85+9V74LltslBxTxazAz9Y6cYXaPPPXjVu8HfwJPEoMA73+BUZAWfFGhIcXhlBBuYLFcXu+lyP5xrtvGqVM4BaIRRGBXwa29x635HG2Ji3inEklS0rMoisdjulg6FeGqQqPy7BM2UWz5YaZn2GaosPyJMCGmN3yBIf/LABjNp1WUgBd6o/FgdqrbAjq3PgJAMbkHE5/7gxSq5pCI+lRwT8VYcZzWaB5eLesq4FDwwAXC6xVw6Y6RiuqxzC6ZCwoPcuNUmkk4zouEaqqpQ4LjnGxj/AQ42D+FG0=
